### ISSUE TITLE
Tile navigation font size & styling

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#100]
- Change tile navigation font weight from bold to semi-bold
- For the larger breakpoint, the type looks big and the line-height looks tight. I tried to check in the developer tools but couldn't see the size -- in the design I have 20 px font size with 25 px line-height. Can we check and adjust this?

**Comment by paulschreiber** [comment]
* Tiles are already using 600 (semibold) and not 700 (bold)
* Font size was 20; bumped line-height to 25px
