### ISSUE TITLE
Add Email and Phone labels to contact info in the footer

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#102]
Add labels preceding the email address and phone number in the site footer. This was already in the design, so we just need to update the live footer to match: https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=575%3A9

This was one of Josh's suggestions from the accessibility audit since the labels provide more context, esp with screen readers.

**Comment by paulschreiber** [comment]
Josh was referring to the `aria-label` attribute, which I added. Putting the words "email" and "phone" in the footer are redundant.
