### ISSUE TITLE
404 Page Button Styling Update

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#105]
- Looking at the screenshot, I think the button radius isn't fully rounded so double-check to see that

- Capitalize "Home" in the button text

<img width="1026" alt="Screen Shot 2020-08-05 at 7 24 46 PM" src="https://user-images.githubusercontent.com/65985453/89600267-77434980-d816-11ea-92f1-8e51f14ae045.png">

Designs: [blue](https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=663%3A296) and [green](https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=663%3A459)

**Comment by paulschreiber** [comment]
Good catch! The line-height on the button was wrong.
