### ISSUE TITLE
Remove vertical scrollbar from homepage

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#110]

**Comment by paulschreiber** [comment]
Changing `min-height` on `<body>` from `100vh` to `97vh` seems to fix this. I am not sure how hacky that is, so I wanted to run it by you first.

**Comment by legarlin** [comment]
@paulschreiber hmm is this `100vh` a problem if you're not logged in as an admin? i'm wondering if it's because of the top admin bar?

**Comment by paulschreiber** [comment]
Oh, right! I hadn't through of that. In that case, we can do calc(100vh - 32px).
