### ISSUE TITLE
Get tile labels to fit on 2 lines -- reducing tile padding on desktop tiles might solve this without changing text size

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#115]
The tiles don't look great when the labels flow to 3 lines -- looks like we might be able to reduce the tile padding slightly without changing the font size, can we check to see if that would work?

<img width="1060" alt="Screen Shot 2020-08-12 at 3 09 00 PM" src="https://user-images.githubusercontent.com/65985453/90073887-e7d2e600-dcae-11ea-9783-3d4e79a6bcc3.png">

**Comment by paulschreiber** [comment]
Fix is visible on https://elections.usdr.dev/campaign-resources/

**Comment by constancias** [comment]
@paulschreiber thank you, looks so good!
