### ISSUE TITLE
Ensure that WP editor/backend works on Chrome

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#117]
When trying to edit pages while using Chrome, the content blocks don't load and the page times out when I click "Update." The issue has been persistent for a few weeks, and I think Legarlin had a similar issue.

We should check on Firefox and other browsers too -- it works fine on Safari, but I imagine a lot of election offices will be working on windows computers and so probably not using that browser.

**Comment by paulschreiber** [comment]
This works fine across browser. @legarlin sent instructions on how to clear out some stale data the site had cached on your machine. This problem is specific to the development team and won't affect actual users.
