### ISSUE TITLE
Improve response to phone number entry in Office Details form 

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#124]
The current logic truncates the first 10 digits of the string that is entered. However, it is common for people to enter 1-(xxx)-xxx-xxxx, and i have also seen someone enter (123)-456-7890/7891. We should show a warning when the string becomes >10 digits, or otherwise handle this gracefully.

**Comment by paulschreiber** [comment]
We now remove leading 1s.
