### ISSUE TITLE
Logo disappears during theme re-install

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#125]
The logo disappears when I've installed a new version of theme. So far, these have all been "manual" theme installs. The logo I'm referring to is set here: https://benbregmanselections.com/wp-admin/admin.php?page=elections.

**Comment by paulschreiber** [comment]
What do you mean by "disappears"? Please provide detailed steps to reproduce.

**Comment by bregman90** [comment]
(1) Manually install and activate theme (e.g. 0.8) during setup
(2) Customize and save a logo here: https://benbregmanselections.com/wp-admin/admin.php?page=elections.
(3) Confirm logo renders in the header on the site.
(4) Manually install and activate theme (0.8.2)
(5) Return to elections settings: https://benbregmanselections.com/wp-admin/admin.php?page=elections
(6) "Logo" has reverted to being unset, and confirmed does not appear in the header on the homepage.

Other settings across the menu - Site Title, Site Description, Theme (Color), Banner (Color), Banner Details, etc. - did not revert to being unset.

![image](https://user-images.githubusercontent.com/4401580/92330075-fe0b6200-f020-11ea-8fc1-e10881695646.png)

**Comment by paulschreiber** [comment]
I believe this was an artifact of the theme folder name changing. This has been fixed in 0.8.6, which renames manually upload zip files.
