### ISSUE TITLE
Handle various image sizes in (major) banner

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#127]
Some images don't render when set as the banner image.

Example: https://benbregmanselections.com:
- Doesn't render: using an image like https://benbregmanselections.com/wp-content/uploads/2020/08/1_screenshot_home.png (2624 by 1984 pixels)
- Does render: using an image like https://benbregmanselections.com/wp-content/uploads/2020/09/1_screenshot_home_small-1.png (200 by 152 pixels)

We should either be clear about size requirements for PNGs in the settings page - or even better, resize and position images to fit the banner. 

The setting page is here: https://benbregmanselections.com/wp-admin/admin.php?page=banner.

**Comment by paulschreiber** [comment]
We do resize the image to fit. To be clear: you were trying to use the screenshot as the banner image?

**Comment by bregman90** [comment]
Correct.

**Comment by bregman90** [comment]
Marking this as "bug" because many admins have tried to put arbitrary images in that banner and have been confused when they don't see it. Can either solve it by rendering something in the banner or preventing choice of certain images at the settings.
