### ISSUE TITLE
"Github.com refuses to connect" when looking for version details for theme

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#128]
In a "theme view" like https://benbregmanselections.com/wp-admin/themes.php?theme=election-websites-0.8.3, there is a button to "view version 0.8.5 details." This button brings up a popup screen that current renders an error message with "Github.com refuses to connect."

Link image: 
![image](https://user-images.githubusercontent.com/4401580/92346332-4490a900-f081-11ea-8ce5-ec36b879c5eb.png)

Error image: 
![image](https://user-images.githubusercontent.com/4401580/92346337-48bcc680-f081-11ea-8b89-8af93da108dc.png)

**Comment by paulschreiber** [comment]
If you see this again, copy the link "view version xxx details" is going to.
