### ISSUE TITLE
Use consistent placeholder text tags

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#130]
On elections.usdr.dev use two variants of each, which, makes automated search/replace harder:

	[Insert: County Name]
	[Insert: County]
	[Insert: State Name]
	[Insert: State]

expected:

	[Insert: County]
	[Insert: State]

**Comment by bregman90** [comment]
Done

**Comment by bregman90** [comment]
Also TODO after this - export latest XML from elections.usdr.dev
