### ISSUE TITLE
Preload a default TOPIC_LIST after theme activation

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#132]
We should preload a TOPIC_LIST for admins after theme activation. 

We can use these topics:
- Voter registration
- Voting by mail
- Voting on Election Day
- Election results
- Poll worker
- COVID 19

**Comment by paulschreiber** [comment]
* What do you mean by `Poll worker`? how to become a poll worker? We should use a more general term, i.e. "election staff"
* Should `Voting on Election Day` by `Voting in person`?

**Comment by paulschreiber** [comment]
Handling this as part of #24.
