### ISSUE TITLE
Create a "develop" branch for contributors

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#135]
The CONTRIBUTING doc (https://github.com/usdigitalresponse/election-websites/blob/master/CONTRIBUTING.md) mentions using a "develop" branch to push changes before merging into master.

We don't currently have a "develop" branch - unless I'm misunderstanding the instructions, does someone (@paulschreiber) need to create it?

**Comment by paulschreiber** [comment]
Done.
