### ISSUE TITLE
Bring back "edit" into admin toolbar for WordPress.com users

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#136]
People who are building the site on WordPress.com do not have an "edit" button in the admin bar while viewing pages. It is really helpful, most people are expecting it.

![image](https://user-images.githubusercontent.com/4401580/93128164-ef0d5b00-f683-11ea-8f00-5bf64977acb0.png)

I shared this with the WordPress.com help desk. They recommended:
(1) Adding the "code-snippets" plugin
(2) Using the following snippet: 
```
function disable_wpcomtoolbar ( $modules ) {
    if ( isset( $modules['masterbar'] ) ) {
      unset( $modules['masterbar'] );
    }
    return $modules;
}
add_filter( 'jetpack_get_available_modules', 'disable_wpcomtoolbar' );
```

If we can automate this during any activation step, great. Otherwise, want to confirm this won't bring up any issues with the theme and that we can go ahead and install this plugin and have admins do this (in which case, we can add it to the doc in GitHub around recommended plugins for WPCOM users).

**Comment by paulschreiber** [comment]
Under no circumstance should folks be adding code snippets. Much better to edit in the settings screen:
https://benbregmanselections.com/wp-admin/admin.php?page=jetpack_modules

We can look in to disabling this in code.

**Comment by bregman90** [comment]
@paulschreiber , tapping that "deactivate" button has no effect.

Help desk also confirmed: "If I recall correctly, the snippet is still needed... [I ask why]... I will pass this feedback along. Ideally, that would be how to turn this off."

**Comment by paulschreiber** [comment]
If tapping the deactivate link isn't working, as support for help. We can put a similar code snippet in the theme if needed. I'll investigate more later.

**Comment by bregman90** [comment]
@paulschreiber, the help desk confirmed that the deactivate link from the settings page you linked is NOT able to fix this. They recommended code snippets; I asked if there any other alternatives and they mentioned "The alternative would be to use SFTP to add this to functions.php."

**Comment by paulschreiber** [comment]
Filed upstream bug https://github.com/Automattic/jetpack/issues/17229

**Comment by paulschreiber** [comment]
I found
