### ISSUE TITLE
Navigation tile: Missing border around settings text field

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#137]
<img width="821" alt="missing_box" src="https://user-images.githubusercontent.com/4401580/93639227-85f05500-f9ad-11ea-818b-234024f737aa.png">

The navigation tile block settings ("Tile" section) is missing a border around the link field ("Page"). Other two fields ("Label", "Icon") do have a border. 

From admin perspective - they are often confused about where to click and that the link is editable.

**Comment by paulschreiber** [comment]
This is a bug in Gutenberg's `<URLInput>` block: https://github.com/WordPress/gutenberg/issues/25524
