### ISSUE TITLE
Automatic updates button/link is missing from theme

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#151]
I checked a few sites, and they all are at version 0.8.8. Version 0.8.9 was pushed [a few days ago](https://github.com/usdigitalresponse/election-websites/releases), and I've usually seen an automatic updates button on the theme plus updates within 24 hours. So opening this issue to track in case something is off.

Picture: 
![image](https://user-images.githubusercontent.com/4401580/94101911-b4bf5e80-fde5-11ea-9850-158f47fa7805.png)

**Comment by paulschreiber** [comment]
Version comparison doesn't properly handle two-digit revision numbers, i.e. 0.8.10 isn't detected as newer than 0.8.9. I'm bumping to 0.9.0.

**Comment by paulschreiber** [comment]
This is definitely working now:
![image](https://user-images.githubusercontent.com/86784/94159863-0b628200-fe52-11ea-8911-7d260d713862.png)

Not sure where you took your screen shot — there's no URL.
