### ISSUE TITLE
There are multiple "Edit page" buttons on a wpengine site

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#153]
In the screenshot below, see the "Edit Page" button in the admin bar, and the "Edit Page" button midway through the screen, overlapping the site.

We only need the one in the admin bar.

This is on a site hosted on WPEngine.

![image](https://user-images.githubusercontent.com/4401580/94102498-1a601a80-fde7-11ea-911e-30f81ac671b4.png)

**Comment by paulschreiber** [comment]
This isn't WPEngine-specific. This is true on any non-WPCOM site. The CSS was fixed in https://github.com/usdigitalresponse/election-websites/commit/bf0c160536fc79f9d2d0bb76362e6d2c517abfe3, but wasn't compiled until 131af90332daf96f32529e3b63affbb261a1de80.
