### ISSUE TITLE
Long text in the homepage banner button breaks the button across multiple lines

### ISSUE THREAD

**Issue by bregman90** [usdigitalresponse/election-websites#165]
Instead breaking the button across lines, we should either:
1) Make the button height large enough for two lines
2) Force the button to be one line only (can do this by resizing font or by truncating text with a "...")

Separately we can also add inline guidance to the settings around banner button text length.

Current behavior: 

![image](https://user-images.githubusercontent.com/4401580/95099799-387e2280-06e5-11eb-857f-d6378736945a.png)

**Comment by paulschreiber** [comment]
We can put a `max-width: 100%' and [truncate](https://css-tricks.com/almanac/properties/t/text-overflow/) like so:
```css
.blah {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
```

We also need to update the documentation and explain the use of short button titles and give examples.
