### ISSUE TITLE
Design 404 page

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#26]

**Comment by constancias** [comment]
@paulschreiber 404 Page designs:

- blue theme: https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=663%3A296

- green theme: https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=663%3A459
