### ISSUE TITLE
Fields for Settings Page

### ISSUE THREAD

**Issue by legarlin** [usdigitalresponse/election-websites#29]
**Banners**
* Front page banner heading
* Front page banner text snippet
* Front page banner link (Learn More)
* Front page banner image?
* Alert banner heading (if different from Front Page)
* Alert banner text snippet (if different from Front Page)
* Alert banner link (if different from Front Page)

**Elections Office Information**
* Registrar Information
* Contact Information
* Social Media accounts??

**Contact Form**
* Subjects

**Comment by paulschreiber** [comment]
Most of this fixed in https://github.com/usdigitalresponse/election-websites/pull/31/.

Fron page banner image.

**Comment by paulschreiber** [comment]
Banner image added.
