### ISSUE TITLE
Create graphic for WordPress themes screen

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#41]
![image](https://user-images.githubusercontent.com/86784/87079154-a05ec300-c1f3-11ea-9f46-3f92fd83d401.png)

**Comment by constancias** [comment]
![Local_elections_website_theme_image](https://user-images.githubusercontent.com/65985453/88442091-03da1a80-cdc8-11ea-8853-59b78db3ca2a.png)

**Comment by constancias** [comment]
@paulschreiber see above image for theme
