### ISSUE TITLE
Design block editor view for Tile block

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#45]

**Comment by constancias** [comment]
@paulschreiber Here's a pass on the UX for the block editor: https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=582%3A0

Feel free to simplify this or otherwise adjust based on what's possible within Wordpress's framework. We can also talk about this if you have any questions

**Comment by paulschreiber** [comment]
@legarlin can we do popovers? or should we use the sidebar? or a placeholder block, like embeds?
