### ISSUE TITLE
style contact form errors

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#48]

**Comment by paulschreiber** [comment]
![image](https://user-images.githubusercontent.com/86784/88711406-229d2180-d0e6-11ea-882a-6c517edcd880.png)

I added some basic styling. Constance: happy to adjust based on your designs.

**Comment by constancias** [comment]
@paulschreiber Try something like this? https://github.com/usdigitalresponse/election-websites/issues/48

In general, it's best practice to put error inline with the fields itself. Thanks for flagging this, I forgot we needed this state!

**Comment by paulschreiber** [comment]
I knew this would get you to make something. :) Staging is updated with your designs.

**Comment by constancias** [comment]
wow, that was fast!!! looks awesome. thanks!
