### ISSUE TITLE
Add labels to icons

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#78]
![image](https://user-images.githubusercontent.com/86784/89197807-447d2500-d57a-11ea-964c-2d802fb364cb.png)

**Comment by paulschreiber** [comment]
1. We'll need to manually have a list of filenames => labels (instead of automated case conversion)
![image](https://user-images.githubusercontent.com/86784/89230795-07348980-d5b2-11ea-9857-3c894939bfba.png)
1. We also need to do the same thing (list of labels) on the collapsible group inspector

**Comment by legarlin** [comment]
how do you create objects in php?

**Comment by paulschreiber** [comment]
We probably don't want objects here, just arrays. i.e.
```php
<?php
$icons = [
'whats-on-the-ballot' => 'What’s on the Ballot',
....
];
```
