### ISSUE TITLE
In editor, show border around collapsible groups

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#80]
![image](https://user-images.githubusercontent.com/86784/89217869-f2003080-d59a-11ea-9873-e9a123340112.png)

@constancias any style suggestions? Maybe a dashed or dotted grey line?

**Comment by legarlin** [comment]
it can just use the same border styles as what's displayed on the frontend

**Comment by paulschreiber** [comment]
Borders will definitely. Let's re-evaulate after the borders are added.
