### ISSUE TITLE
tiles have double-encoded HTML

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#84]
Example page:
https://elections.usdr.dev/wp-admin/post.php?post=9&action=edit

![image](https://user-images.githubusercontent.com/86784/89230697-d2c0cd80-d5b1-11ea-8623-748de1623ab4.png)

Also happens in the inspector:
![image](https://user-images.githubusercontent.com/86784/89231366-2d0e5e00-d5b3-11ea-9cf6-6ac53a110ddd.png)

**Comment by paulschreiber** [comment]
This happens in the backend only; looks ok on the front end.

**Comment by paulschreiber** [comment]
This particular tile should be `Military and Overseas Voting` (no ampersand0, but we should fix the bug.

**Comment by legarlin** [comment]
i can't seem to repro this locally. what happens if you make the edit to "Military & Overseas Voting" and resave? Does it reload like that when you reopen the edit page?

I also can't seem to make updates to the staging website pages..

**Comment by paulschreiber** [comment]
Hmm. I can't re-created this. Will refile with more detailed steps if it happens again.

**Comment by legarlin** [comment]
ah i am able to recreate this in safari on the staging website, but no luck locally :/ are you aware of environment differences that might cause this?

**Comment by paulschreiber** [comment]
I wonder if it's WordPress 5.4 vs 5.5. Can you try upgrading to 5.5 locally?

**Comment by legarlin** [comment]
sure i'll give that a shot

**Comment by legarlin** [comment]
closing since its not an issue with the stable 5.4.2 and no longer an issue with the latest 5.5 when we reinstalled the beta
