### ISSUE TITLE
style :focus in non-blue color

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#86]

**Comment by constancias** [comment]
@paulschreiber 

We could use the light-blue color and the light-green color for the focus state, each color is different than the main theme's blue/green but we could swap them if we want them to really stand out (so light-green focus state for the blue theme and light-blue focus state for the green theme)

2 px border width on the line

https://www.figma.com/file/t1FrrSisgLvtZZpcvYt9PU/CTCL_Website?node-id=125%3A4249
