### ISSUE TITLE
Fix mobile view grid padding for tile navs

### ISSUE THREAD

**Issue by legarlin** [usdigitalresponse/election-websites#88]

**Comment by legarlin** [comment]
16px all around, 10px in the row/column gaps

**Comment by paulschreiber** [comment]
@legarlin I redid some of this and cleaned it up a bit, but am not sure how to make the exterior padding 16px at all sizes, given the grid-template-columns and the `vw` units.

**Comment by legarlin** [comment]
ooh i saw the change! i think the exterior padding/margin will live on the wrapping element for the grid! is that what you mean? the margins around aren't baked into the grid specs itself :)

**Comment by legarlin** [comment]
ah i don't quite know how to do that to be honest without introducing javascript. 

and I think the margins end up not consistently staying at 16px depending on screen size because the tiles don't scale automatically. the only CSS thing that I can think of that could potentially mitigate that is by specifying a margin that fills in the remaining percentages of the `vw` units. it wouldn't be precise, but it may be even at least.

otherwise, to maintain square tiles, I think we'd need to introduce javascript to measure the width and set that to the height. is that a route we want to go down?

**Comment by paulschreiber** [comment]
Can we set with width of each tile to calc (100% - 42px)? Not sure what we could do for the height.

**Comment by legarlin** [comment]
oh actually i think potentially we could do  `100vw - 42px` for both because i _think_ `vw` is specifically for width and `vh` is height. let me try

**Comment by legarlin** [comment]
ok i just updated staging with this.

one thing to note is that these are truly square now in mobile view (height and width are set to the same value) whereas in desktop view, they're slightly offset a bit. @constancias should we apply an aspect ratio to the height calculation?

**Comment by legarlin** [comment]
will close for now until we hear back about ^ or we can file a new issue

**Comment by constancias** [comment]
@legarlin If it's not too hard then applying an aspect ratio would be nice. I think would shave 10-12 px off the mobile tiles, which would push more content up into view for each scroll. But no worries it turns out to be a pain or would be super time-consuming.

**Comment by legarlin** [comment]
done, used a 0.9 ratio which is ~ the ratio of the desktop and tablet heights. we can adjust if needed!
