### ISSUE TITLE
Markup and styles for FAQ

### ISSUE THREAD

**Issue by paulschreiber** [usdigitalresponse/election-websites#9]
![image](https://user-images.githubusercontent.com/86784/84830261-20c84480-aff7-11ea-9bfd-7678c99d41ae.png)

**Comment by paulschreiber** [comment]
Sub-section need styling. @legarlin are you still working on the block behaviour/markup? I don't want to make CSS changes if that's the case.
![image](https://user-images.githubusercontent.com/86784/89125957-00bde900-d4b0-11ea-81ac-7a5789a29049.png)

**Comment by legarlin** [comment]
this should be done

**Comment by legarlin** [comment]
note the staging FAQ page/content will likely need to be remade since i reworked the editor experience.
