### ISSUE TITLE
Fix tile nav padding - mobile layout view

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#92]
See comments in [mobile QA deck](https://docs.google.com/presentation/d/18f83jmIf4T7WzcE9Zgn7uKsU5GR9TA0Kl_eoV4k3MZ4/edit#slide=id.g86bc964ca3_0_66) 

Side padding left/right should be 16 px
inner padding between tiles (horizontally and vertically) can be 10 px

**Comment by paulschreiber** [comment]
Duplicate of #88
