### ISSUE TITLE
Size and re-size icons proportionally

### ISSUE THREAD

**Issue by constancias** [usdigitalresponse/election-websites#99]
Currently it looks like some of the icons appear smaller than others, so whatever sizing/re-sizing is being applied looks like it might not be perfectly consistent. Right now it's most noticeable that these icons are smaller than the rest:

- Poll worker/election worker
- Vote by mail
- Register by mail
- Campaign resources
- Accessible voting
- Voter's choice act

<img width="672" alt="Screen Shot 2020-08-05 at 3 03 15 PM" src="https://user-images.githubusercontent.com/65985453/89468662-d167e000-d72c-11ea-82cd-5033bacf47ed.png">

**Comment by paulschreiber** [comment]
@constancias can you look at the SVGs in https://github.com/usdigitalresponse/election-websites/tree/master/theme/assets/images/icons and see if they exported at different sizes?

**Comment by constancias** [comment]
@paulschreiber It looks like the exported 1:1 from the designs correctly -- are you doing anything to constrain the widths or fit them into a certain shape? That might be causing them to resize at different sizes since they aren't all the same width.

**Comment by paulschreiber** [comment]
All of the icons are 50x50 in the code. The problem appears to be the bounding boxes in the SVGs:
![image](https://user-images.githubusercontent.com/86784/89490178-385fb600-d77a-11ea-97b8-e528cce37f4c.png)

Can you adjust them so they are snug?

**Comment by paulschreiber** [comment]
https://github.com/usdigitalresponse/election-websites/blob/master/theme/assets/images/icons/blue/vote-by-mail.svg

![image](https://user-images.githubusercontent.com/86784/89490635-4d891480-d77b-11ea-92ad-0bc8575822b7.png)

**Comment by constancias** [comment]
Here is the blue set of rebuilt icons with 50x50 bounding box -- will upload the green set after I finish them

[Blue icons rebuilt.zip](https://github.com/usdigitalresponse/election-websites/files/5036364/Blue.icons.rebuilt.zip)

**Comment by constancias** [comment]
@paulschreiber Here is the set of green icons rebuilt.

I re-added the icon for "find voting location" that you mentioned -- we're not currently using it in the design but we might as well include it since it would be good for use cases where they're using an address look-up tool instead of a table view. Also realized that I might have given you a bad version of the blue mask person icon so re-uploading that one too. Sorry for all the changes!

[Green icons rebuilt.zip](https://github.com/usdigitalresponse/election-websites/files/5037966/Green.icons.rebuilt.zip)

[Person_mask_and_find_voting_location_blue.zip](https://github.com/usdigitalresponse/election-websites/files/5037970/Person_mask_and_find_voting_location_blue.zip)
